server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /doc/swagger-ui/index.html

spring:
  application:
    name: msavion
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_avion_dev?createDatabaseIfNotExist=true
    username: root
    password: ''
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/db_avion_test?createDatabaseIfNotExist=true
    username: root
    password: ''
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/db_avion_prod?createDatabaseIfNotExist=true
    username: root
    password: ''
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none